[project]
name = "02-2025-vector-search"
version = "0.1.0"
description = "LLM zoomcamp 2025:Modulo 2 vector-search"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "notebook>=7.4.3",
    "qdrant-client[fastembed]>=1.14.2",
]
